/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GameWindow.java
 *
 * Created on 2010-nov-04, 23:48:49
 */

package worldofaircraft;

import physics.Material;
import physics.entities.Plane;
import java.awt.CardLayout;
import java.awt.Rectangle;
import java.util.ArrayList;

/**
 *
 * @author Robinerd
 */
public class GameWindow extends javax.swing.JFrame{

	private PaintLayer paintArea;
	private GamePanel game;
	private ArrayList<Rectangle> walls;

    /** Creates new form GameWindow */
    public GameWindow() {
        initComponents();

		setFocusable(true); //Fönstret requestar fokus varje gång simulationen startas

		paintArea = new PaintLayer();
		paintAreaContainer.add(paintArea);
		paintArea.setSize(paintAreaContainer.getSize());
		paintArea.setPreferredSize(paintAreaContainer.getSize());

		game = new GamePanel();
		gamePanelCanvas.add(game);
		addKeyListener(game.getInputManager());
    }


	

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sizeButtonGroup = new javax.swing.ButtonGroup();
        leftClickButtonGroup = new javax.swing.ButtonGroup();
        rightClickButtonGroup = new javax.swing.ButtonGroup();
        designCard = new javax.swing.JPanel();
        paintAreaContainer = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        radioRubber = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        radioWings = new javax.swing.JRadioButton();
        radioStructure = new javax.swing.JRadioButton();
        clearButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        radioJoint = new javax.swing.JRadioButton();
        radioWheel = new javax.swing.JRadioButton();
        radioEngine = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        radioSize7 = new javax.swing.JRadioButton();
        radioSize15 = new javax.swing.JRadioButton();
        radioSize25 = new javax.swing.JRadioButton();
        radioSize60 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        inGameCard = new javax.swing.JPanel();
        gamePanelCanvas = new javax.swing.JPanel();
        stopButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout paintAreaContainerLayout = new javax.swing.GroupLayout(paintAreaContainer);
        paintAreaContainer.setLayout(paintAreaContainerLayout);
        paintAreaContainerLayout.setHorizontalGroup(
            paintAreaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        paintAreaContainerLayout.setVerticalGroup(
            paintAreaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        leftClickButtonGroup.add(radioRubber);
        radioRubber.setText("Rubber");
        radioRubber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRubberActionPerformed(evt);
            }
        });

        jLabel5.setText("Left Click:");

        leftClickButtonGroup.add(radioWings);
        radioWings.setSelected(true);
        radioWings.setText("Wings");
        radioWings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioWingsActionPerformed(evt);
            }
        });

        leftClickButtonGroup.add(radioStructure);
        radioStructure.setText("Structure");
        radioStructure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioStructureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(radioWings)
                    .addComponent(radioStructure)
                    .addComponent(radioRubber))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioWings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioStructure)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioRubber)
                .addGap(23, 23, 23))
        );

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Right click:");

        rightClickButtonGroup.add(radioJoint);
        radioJoint.setSelected(true);
        radioJoint.setText("Joint");
        radioJoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioJointActionPerformed(evt);
            }
        });

        rightClickButtonGroup.add(radioWheel);
        radioWheel.setText("Wheel");

        rightClickButtonGroup.add(radioEngine);
        radioEngine.setText("Engine");
        radioEngine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEngineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioEngine)
                    .addComponent(radioWheel)
                    .addComponent(radioJoint)
                    .addComponent(jLabel6))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioJoint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioWheel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioEngine)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sizeButtonGroup.add(radioSize7);
        radioSize7.setSelected(true);
        radioSize7.setText("7");
        radioSize7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSize7ActionPerformed(evt);
            }
        });

        sizeButtonGroup.add(radioSize15);
        radioSize15.setText("15");
        radioSize15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSize15ActionPerformed(evt);
            }
        });

        sizeButtonGroup.add(radioSize25);
        radioSize25.setText("25");
        radioSize25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSize25ActionPerformed(evt);
            }
        });

        sizeButtonGroup.add(radioSize60);
        radioSize60.setText("60");
        radioSize60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSize60ActionPerformed(evt);
            }
        });

        jLabel1.setText("Brush size:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(radioSize7)
                    .addComponent(radioSize15)
                    .addComponent(radioSize25)
                    .addComponent(radioSize60))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSize7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSize15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSize25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSize60)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout designCardLayout = new javax.swing.GroupLayout(designCard);
        designCard.setLayout(designCardLayout);
        designCardLayout.setHorizontalGroup(
            designCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(designCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(designCardLayout.createSequentialGroup()
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton))
                    .addComponent(paintAreaContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(designCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        designCardLayout.setVerticalGroup(
            designCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(designCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(designCardLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, designCardLayout.createSequentialGroup()
                        .addComponent(paintAreaContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(designCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startButton)
                            .addComponent(clearButton))))
                .addContainerGap())
        );

        getContentPane().add(designCard, "card3");

        gamePanelCanvas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout gamePanelCanvasLayout = new javax.swing.GroupLayout(gamePanelCanvas);
        gamePanelCanvas.setLayout(gamePanelCanvasLayout);
        gamePanelCanvasLayout.setHorizontalGroup(
            gamePanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        gamePanelCanvasLayout.setVerticalGroup(
            gamePanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inGameCardLayout = new javax.swing.GroupLayout(inGameCard);
        inGameCard.setLayout(inGameCardLayout);
        inGameCardLayout.setHorizontalGroup(
            inGameCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inGameCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inGameCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gamePanelCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stopButton))
                .addContainerGap())
        );
        inGameCardLayout.setVerticalGroup(
            inGameCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inGameCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamePanelCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stopButton)
                .addContainerGap())
        );

        getContentPane().add(inGameCard, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

	//event för att avsluta designfasen
	private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
		Plane plane = paintArea.assemblePlane();
		game.startFlight(plane);
		requestFocus();
		
		((CardLayout) getContentPane().getLayout()).next(getContentPane());
	}//GEN-LAST:event_startButtonActionPerformed

	private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
		game.stop();
		((CardLayout) getContentPane().getLayout()).next(getContentPane());
	}//GEN-LAST:event_stopButtonActionPerformed

	private void radioWingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioWingsActionPerformed
		paintArea.setPaintMaterial(Material.WING_MATERIAL);
	}//GEN-LAST:event_radioWingsActionPerformed

	private void radioStructureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioStructureActionPerformed
		paintArea.setPaintMaterial(Material.STRUCTURE_MATERIAL);
	}//GEN-LAST:event_radioStructureActionPerformed

	private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
		paintArea.clear();
	}//GEN-LAST:event_clearButtonActionPerformed

	private void radioRubberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRubberActionPerformed
		paintArea.setPaintMaterial(Material.NULL_MATERIAL);
	}//GEN-LAST:event_radioRubberActionPerformed

	private void radioSize7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSize7ActionPerformed
		paintArea.setBrushSize(7);
	}//GEN-LAST:event_radioSize7ActionPerformed

	private void radioSize15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSize15ActionPerformed
		paintArea.setBrushSize(15);
	}//GEN-LAST:event_radioSize15ActionPerformed

	private void radioSize25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSize25ActionPerformed
		paintArea.setBrushSize(25);
	}//GEN-LAST:event_radioSize25ActionPerformed

	private void radioSize60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSize60ActionPerformed
		paintArea.setBrushSize(60);
	}//GEN-LAST:event_radioSize60ActionPerformed

	private void radioEngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEngineActionPerformed
		paintArea.setRightClickAction(PaintLayer.PLACE_ENGINE);
	}//GEN-LAST:event_radioEngineActionPerformed

	private void radioJointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioJointActionPerformed
		paintArea.setRightClickAction(PaintLayer.PLACE_JOINT);
	}//GEN-LAST:event_radioJointActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel designCard;
    private javax.swing.JPanel gamePanelCanvas;
    private javax.swing.JPanel inGameCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.ButtonGroup leftClickButtonGroup;
    private javax.swing.JPanel paintAreaContainer;
    private javax.swing.JRadioButton radioEngine;
    private javax.swing.JRadioButton radioJoint;
    private javax.swing.JRadioButton radioRubber;
    private javax.swing.JRadioButton radioSize15;
    private javax.swing.JRadioButton radioSize25;
    private javax.swing.JRadioButton radioSize60;
    private javax.swing.JRadioButton radioSize7;
    private javax.swing.JRadioButton radioStructure;
    private javax.swing.JRadioButton radioWheel;
    private javax.swing.JRadioButton radioWings;
    private javax.swing.ButtonGroup rightClickButtonGroup;
    private javax.swing.ButtonGroup sizeButtonGroup;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables

}
